### PR TITLE
fix: errors were not bubbling appropriately from sub-commands to top-level

### PR DESCRIPTION
**Pull request by bcoe**
fixes: #794 

@lhecker thanks for the bug report, if you have a second would love for you to test out this fix; we'll have it released to `npm cache clear; npm i yargs@next` in an hour or so.

### CODE REVIEW

**Comment by lhecker** [comment]
@bcoe I fell quite ill yesterday (40°C fever yay) and thus don't really feel like coding right now... 😅
But I'll make sure to test it properly as soon as I'm better again in the coming days. 🙂

**Comment by bcoe** [comment]
@lhecker get feeling better 👍 

changes are ready for you, as soon as you're ready: `npm cache clear; npm i yargs@next`.

**Comment by lhecker** [comment]
@bcoe Oh now I completely forgot to comment on here… Sorry. ☹️
It works flawless of course! Thanks for this PR. 🙂

**Comment by bcoe** [comment]
@lhecker awesome, thanks for the help testing -- please continue reporting any weird issues you bump into.

**Pull request merged**
