### PR TITLE
feat: split demand() into demandCommand()/demandOption()

### LINKED ISSUE #504: separate demand into demandOption and demandCommand
As @ljharb was fixing #431 with #438 , we've discovered a bit of a black hole that is `demand`. 

The suggested solution at this point is to work off `demand` being separated in to two different functions: `demandOption` and `demandCommand`, clear detailed in [this comment](https://github.com/yargs/yargs/pull/438#issuecomment-200545670). 

I am currently working on separating the two. To avoid breaking too many things, I am hoping to keep both `require` and `demand` as a alias for `demandOption` until we decide to completely get rid of `demand`. 

Let's use this thread to track any discussion we might have about `demand` and the proposed separation.

### PR DESCRIPTION
**Pull request by bcoe**
Getting @lrlna's wonderful work on splitting `demand()` into `demandCommand()`/`demandOption()` over the finish line.

Everything is %99 of the way there, just addressing some final nits from @maxrimue and myself -- excited to try to get yargs down to a few less open issue.

TODO:

- [x] add a few more tests, specifically one for #438.

fixes #504, #431 follow up with #618

### CODE REVIEW

**Comment by bcoe** [comment]
@ljharb sorry this turned into a never ending yak shave! The `demand()` API was pretty all over the place, and it took quite a bit of refactoring to get things to where we wanted them.

Any ways, months overdue but I think this gets things to what you pushed us towards. Thanks @lrlna for the hard work 🎉

**Comment by ljharb** [comment]
Thanks to everybody :-) I look forward to consuming it once it's released.

**Comment by bcoe** [comment]
@ljharb @maxrimue @lrlna this is queued up to go out with the next `latest` release of yargs. I would love your help testing since `6.6.0` is a big one:

`npm cache clear; npm i yargs@next`

**Comment by lrlna** [comment]
@bcoe are you doing this one as a major though? Or with `6.6.0` ?

**Comment by bcoe** [comment]
@lrlna since we opted to keep the `demand()` method for the time being, I see no reason to bump a major; however, I'm starting to picture what a `7.x` release would look like. I would love to solve these problems specifically:

* alert when you're off the rails of the API: https://github.com/yargs/yargs/issues/739
* don't catch program errors: https://github.com/yargs/yargs/issues/455
* do some more work around whether options are applied globally.

CC: @nexdrew, @maxrimue

**Comment by maxrimue** [comment]
@bcoe I think that sounds like a good plan. What do you think when should we take action about the readme refactoring?

**Comment by bcoe** [comment]
@maxrimue I approve of this message; I've noticed _a lot_ of big JS projects have moved towards smaller READMEs with external doc sites.

**Comment by bcoe** [comment]
@maxrimue want to start pulling together a `v7` thread? I loved how you helped with release management last time.

**Comment by maxrimue** [comment]
@bcoe on it

**Comment by kumar303** [comment]
As of 6.6.0, `demand()` did slightly regress. The custom message is no longer displayed. That's ok though -- our tests failed, we read the readme, learned about the deprecation, and switched to the new methods :) Thanks for keeping a concise changelog.

**Comment by bcoe** [comment]
@kumar303 mind sharing the syntax that had a regression for you, I'd like to patch this in the `6.x` stream.

**Comment by kumar303** [comment]
Sure, here is a script to reproduce it:

````javascript
var yargs = require('yargs');
yargs
  .help('help')
  .demand(0, 0, 'This is a custom message to explain the error better')
  .strict()
  .argv;
````

In `yargs@6.6.0`:
````
$ node script.js nope
Options:
  --help  Show help                                                    [boolean]

Too many non-option arguments: got 1, maximum of 0
````

In `yargs@6.5.0`:
````
$ node script.js nope
Options:
  --help  Show help                                                    [boolean]

This is a custom message to explain the error better
````

**Comment by bcoe** [comment]
@kumar303 thank you; I'll get a regression test written this evening.

**Pull request merged**
