### PR TITLE
docs: describe commandDir() parameters (#1540)

### PR DESCRIPTION
**Pull request by bennyn**
The `commandDir` option is explained in [Advanced Topics](https://github.com/yargs/yargs/blob/master/docs/advanced.md) but missing from the API list.

### CODE REVIEW

**Comment by bcoe** [comment]
@bennyn thanks for the contribution 👍 I'm excited to document this.

One thing jumps out at me, the formatting is a bit off compared to how we've documented parameters elsewhere in the doc:

https://github.com/yargs/yargs/blob/master/docs/api.md#commandmodule

Where we've just used a paragraph per parameter, with the parameter starting in `back-ticks`, mind matching this formatting?

**Comment by bennyn** [comment]
Hey @bcoe, I will update my PR matching your style guide!

**Comment by bennyn** [comment]
@bcoe Style updated! 👍

**Comment by bcoe** [comment]
@bennyn thank you for the contribution \o/

**Pull request merged**
