### PR TITLE
chore(ts): init typescript conf + tsify is-promise

### PR DESCRIPTION
**Pull request by mleguen**
First step of #1586.

It should not have any impact on user projects (neither js nor ts).

Includes linting of ts code.

Tested with `npm pack` too: the only change in the package file list is the replacement of `lib/is-promise.js` by the compiled `build/lib/is-promise.js`.

EDIT: updated path now that ts files are also in the lib dir

### CODE REVIEW

**Comment by bcoe** [comment]
@mleguen convince you to try out https://www.npmjs.com/package/gts for linting? this would help keep yargs consistent with the TypeScript configuration I use at work, which would be awesome.

**Comment by mleguen** [comment]
@bcoe In fact, I used standard to keep yargs consistent between js and ts linting, but no problem for me: always ready to try some new tool :-)

**Comment by bcoe** [comment]
@mleguen depending on our timeline, I'd love for us to test `2.x.x`, which requires Node 8, but has a variety of improvements -- it could be used for both our JS and TypeScript linting.

**Comment by mleguen** [comment]
@bcoe What I finally did not to block this PR is to use gts 2.x only for the ts configuration (and script names).

We could later use it for linting too as soon as we drop support for node 8 (but let's not fight 2 battles at the same time).

**Comment by mleguen** [comment]
@bcoe ready for review

**Comment by mleguen** [comment]
@bcoe I tsified test/is-promise too in this PR to stay coherent

**Pull request merged**
