### PR TITLE
feat(locale): added hebrew translation

### PR DESCRIPTION
**Pull request by mendlero**
added hebrew translation.

### CODE REVIEW

**Review by shadowspawn — APPROVED** [review]
LGTM

Thanks @mendlero

**Review by shadowspawn — CHANGES_REQUESTED** [review]
Prompted by #2361, should add Hebrew to supported translations in documentation too.

**Comment by mendlero** [comment]
on it

**Review by shadowspawn — APPROVED** [review]
I meant just the Hebrew, but hopefully will merge ok with the other PR! 😄

**Comment by bcoe** [comment]
Thank you for the contribution 🎉

**Pull request merged**
