### PR TITLE
fix: groups were not being maintained for nested commands

### LINKED ISSUE #1081: Group of global options lost on child command
I found that the groups do not propagate down to child commands, though the options do. Sample code:

```typescript
let yargs = Yargs
    .strict()
    .help('h')
    .alias('h', 'help')
    .option('logFacility', {
        description: 'sets the log facility',
        default: process.env.LOGFACILITY || 'default',
        choices: ['console', 'file', 'null', 'default']
    })
    .option('logFile', {
        description: 'the log file (without extension) to be used by the "file" log facility',
        string: true,
        default: process.env.LOGFILE || path.join('logs', 'command')
    })
    .option('logRotate', {
        description: 'controls how and when the log file is rotated',
        string: true,
        default: process.env.LOGROTATE || '1D:2:5'
    })
    .option('logLevel', {
        description: 'controls the level of logging; the default is taken from the LOGLEVEL environment variable if possible, or defaults to "info"',
        default: process.env.LOGLEVEL || 'info',
        choices: ['none', 'error', 'warning', 'info', 'debug']
    })
    .group(['logFacility', 'logFile', 'logLevel', 'logRotate'], 'Logging')
    .global(['development', 'logFacility', 'logFile', 'logLevel', 'logRotate'])
    .strict()
    .commandDir('commands');
```

If I execute "node index --help", I see my those logging options in the "Logging" group.
If I execute "node index sub-command --help", they are no longer grouped but the options marked as global appear mixed in with the sub-commands options.

The only workaround I have currently is to specify the "group" at every command level.

### LINKED ISSUE #1173: Subcommands only display option groupings of its own options and the option of its parent command
If calling a subcommand with `--help`/`help`, it will only print groupings that were defined in the command itself, or the parent-command, but ignoring any groupings that were made in (anchestor-)commands further up the nesting, or in the global context:

**MCVE:**
`test.js`

```
const yargs = require('yargs');

yargs.option('foo').group(['foo'], 'Foo-Flags:');

yargs.command({
    command: 'com',
    describe: 'The Command',
    builder: yargs => {
        yargs.option('bar').group('bar', 'Bar-Flag:');

        yargs.command({
            command: 'subcom',
            describe: 'The Subcommand',
            builder: yargs => {
                yargs.option('baz').group('baz', 'Baz-Flag:');

                yargs.command({
                    command: 'subsubcom',
                    describe: 'The Subsubcommand',
                    builder: yargs => {
                        yargs.option('quax').group('quax', 'Quax-Flag:');
                    }
                });
            }
        });
    }
});

yargs.parse();
```

**Expected behavior:**
```
node test.js com subcom subsubcom --help

The Subsubcommand

Quax-Flag:
  --quax

Baz-Flag:
  --baz

Bar-Flag:
  --bar

Foo-Flags:
  --foo

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

**Actual behavior:**
```
node test.js com subcom subsubcom --help

The Subsubcommand

Quax-Flag:
  --quax

Baz-Flag:
  --baz

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --foo
  --bar
```

### PR DESCRIPTION
**Pull request by mleguen**
Closes #1173, closes #1081.

### CODE REVIEW

**Comment by mleguen** [comment]
Thanks Karl Horky for pointing out that `Closes a, b` in the PR description would only have closed the 1st issue, not the 2nd one. This is correct for Gitlab, not for Github which requires `Closes a, closes b`.

**Comment by karlhorky** [comment]
No worries, glad to help! Thanks for the PR!

**Comment by bcoe** [comment]
@mleguen when you get a second to confirm, this fix should have been released in `14.2.0`.

**Comment by mleguen** [comment]
Thanks @bcoe , looks good to me.

**Pull request merged**
