### PR TITLE
Upgrade Levenshtein to Damerau-Levenshtein

### PR DESCRIPTION
**Pull request by thrien**
Minor improvement for convenience. The Damerau-Levenshtein distance considers transpositions (which are common in mistyped strings) as one edit.

### CODE REVIEW

**Comment by bcoe** [comment]
@thrien thanks for the contribution 👏 , this code certainly hasn't been touched in a long time.

**Comment by bcoe** [comment]
@thrien tests are failing due to a slight drop in coverage, it looks like line 57 of the new algorithm isn't exercised. Could we add a test case?

**Comment by thrien** [comment]
Line 57 is the new case that counts as one edit (transposition). So it makes sense that it doesn't get tested.

I will try to add a test, even though i don't really know how tests work.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@thrien thank you for the contribution 👏

**Comment by mrlubos** [comment]
Thanks @thrien!

**Pull request merged**
