### PR TITLE
fix(deno): update types for deno ^1.4.0

### PR DESCRIPTION
**Pull request by luke-john**
In version 1.4 Deno adopted;

- the tsconfig setting [importsNotUsedAsValues](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues) - https://github.com/denoland/deno/pull/7413
- the tsconfig setting [isolatedModules](https://www.typescriptlang.org/tsconfig#isolatedModules) when using the deno `--unstable` flag - https://github.com/denoland/deno/issues/7326 ([intended to be enabled by default in 1.5](https://github.com/denoland/deno/issues/7326))

These require the use of;
- type only imports for values which are only used as types (`importsNotUsedAsValues`)
- type only exports for types which are re-exported (`isolatedModules`)

I've added more details at https://github.com/yargs/yargs/issues/1771.

related prs:
- yargs-parser https://github.com/yargs/yargs-parser/pull/329
- y18n https://github.com/yargs/y18n/pull/100

### CODE REVIEW

**Comment by luke-john** [comment]
While preparing this pr and the related ones in yargs-parse and y18n, vscode showed most files as full of errors due to the use of file extensions in imports which don't match the actual source files extension

ie

```ts
// https://github.com/yargs/yargs/blob/master/lib/typings/yargs-parser-types.ts#L3
import type { Dictionary, ValueOf } from './common-types.js'
```

In this example common-types is a typescript file with the extension `.ts` `common-types.ts`

While there's some build tooling and to support the builds to the build folder, I was still seeing issues in the files under `/build`.

Are these intentional (possibly for the cjs builds)?

**Comment by bcoe** [comment]
@luke-john I will need to dig into these CI/CD issues, I just fixed a bug related to how we parse commands, not sure how I failed to update this failing test.

**Comment by luke-john** [comment]
No problems, I've just updated this to be against master instead of Deno.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@luke-john hey Luke, just wanted to let you know that the latest version of yargs should have this problem fixed for you.

Let me know if you continue to bump into any issues?

**Pull request merged**
