### PR TITLE
feat(completion): takes negated flags into account when boolean-negation is set

### LINKED ISSUE #1431: Completions should suggest `--no-*` flags when appropriate
When a boolean flag defaults to `true`, I pass `--no-foo` to set it to false.

yargs tab-completions should propose the `--no-foo` flag when:

a) default for the flag is `true`
b) the yargs parser is configured to allow `--no-*` variants for boolean flags.

EDIT fixed a typo that I had backwards

### PR DESCRIPTION
**Pull request by mleguen**
Closes #1431 

When boolean-negation is set:
- completes --no-flag when flag defaults to true
- avoids repeating flags whose negated counterpart is already present

### CODE REVIEW

**Comment by mleguen** [comment]
Warning : either this PR or #1508 will need some conflict-handling before merging, as both impact the same lines in completion.js.

**Comment by bcoe** [comment]
:+1: let's hold off on landing until we have a plan. Perhaps you could make a PR against this PR, for #1508 rather than us having both PRs open at the same time.

**Comment by mleguen** [comment]
I wronlgy mentionned #1508, but is #1507 which should conflict with this PR.

Instead of doing something complicated, let's merge #1507 first (I will need reviewing first), and I will then rebase this PR.

**Comment by bcoe** [comment]
@mleguen bother you to rebase?

**Comment by mleguen** [comment]
@bcoe I should have some time to do it next week

**Comment by mleguen** [comment]
@bcoe done!

**Pull request merged**
