### PR TITLE
feat: deprecate command

### PR DESCRIPTION
**Pull request by laggingreflex**
More work towards #1518

Still a work in progress. 

This is turning out to be a bigger change. Thought I'd ask for opinions before continuing. 

The big parts are the two main refactors: https://github.com/yargs/yargs/commit/9717c2031ae834159f7ff23d8eb943be6f856f9f & https://github.com/yargs/yargs/commit/ffd71e168bfdf830bb2bce0503664e1fdad3fedf, latter one still a work in progress (~50 failing tests ). 

If those are done properly, the feature itself seems pretty simple: https://github.com/yargs/yargs/commit/c71531976d2f30b2f1f566e163db94bb138d5ffe

Should I carry on with the refactor? Or would it be considered too large a change for a small feature?

### CODE REVIEW

**Comment by bcoe** [comment]
> Should I carry on with the refactor? Or would it be considered too large a change for a small feature?

I'm wondering if we could figure out a way to add this feature without a significant overall to commands. Commands being a fairly finicky part of the codebase.

How were you picturing that you would specify a deprecated command? It feels like if we simply made this an additional property on the command itself, like the `handler`, or `builder`, it shouldn't be too hard to output a deprecation warning without a significant refactor.

**Comment by laggingreflex** [comment]
My basic assumption is that this has to be done [here][1], which is what https://github.com/yargs/yargs/commit/c71531976d2f30b2f1f566e163db94bb138d5ffe does (but that uses the refactor). 

Without the refactor the `command` there is an array which traces back to

* [`Usage.command`][2] 
* [`Command.addHandler`][3]

The `cmd` there (or any other object) doesn't seem to be available there to attach a property (`deprecated`). 

It's all arrays and params list. 

I could add the `deprecated` as another param?

```js
  -self.command = function command (cmd, description, isDefault, aliases) {
  +self.command = function command (cmd, description, isDefault, aliases, deprecated) {
```

Initially I did go this route and found a lot of tests failing this way too (hence may have required a big change too). Should I try it this way?



[1]: https://github.com/yargs/yargs/blob/master/lib/usage.js#L214
[2]: https://github.com/yargs/yargs/blob/master/lib/usage.js#L109
[3]: https://github.com/yargs/yargs/blob/master/lib/command.js#L74

**Comment by bcoe** [comment]
@laggingreflex I think adding it as an additional parameter would be reasonable, even though it's a bit ugly. Maybe it's good that your `.command` code is a bit ugly if the command is deprecated, reminds you to actually drop the function eventually.

**Comment by bcoe** [comment]
@laggingreflex want to rebase, and we can see this over the finish line? I think this is a great feature.

**Comment by laggingreflex** [comment]
Please checkout #1624. It makes fewer changes.

**Pull request closed without merging**
