### PR TITLE
fix: defer exiting, don't panic w/ .exit()

### PR DESCRIPTION
**Pull request by eljefedelrodeodeljefe**
Fixes: https://github.com/yargs/yargs/issues/497

Please don't take this too seriously, I have never used yargs, but am playing with a solution to the problem.

This would pass tests. I am not sure whether it is API compatible.

### CODE REVIEW

**Comment by eljefedelrodeodeljefe** [comment]
Had to push a second commit for 0.10 builds

**Comment by eljefedelrodeodeljefe** [comment]
added commit for nextTick. Also a test on Windows is breaking for v6. We'll see.

**Comment by addaleax** [comment]
Opened a PR for the windows issue at https://github.com/tapjs/spawn-wrap/pull/21. :)

**Comment by eljefedelrodeodeljefe** [comment]
Awesome! CI Failure then unrelated...

**Comment by bcoe** [comment]
executing on `next_tick` will definitely break the contract that yargs has with existing implementors, the expectation is that yargs would exit before the first line of user-code executes if an event has occurred that should cause yargs to terminate.

As usual, a busy week at npm but I will have some hacking time this weekend to land some Node 6 fixes with people's help 👍

**Comment by eljefedelrodeodeljefe** [comment]
I dropped the commit then. I leave it be and defer to you w/ the fix then. Also reworded PR and commit to have friendlier language cc @addaleax

**Comment by addaleax** [comment]
Yeah, sorry, I haven’t kept track of the discussion in Node core on how exiting is best handled in cases like this, so I probably won’t be much of a help here. And I’m not even sure it’s possible to do this correctly while still keeping the contract with dependents of yargs as mentioned by @bcoe… but I might be mistaken.

**Comment by eljefedelrodeodeljefe** [comment]
Yeah no worries. Just mentioned you for the rename. Also I think your assumption is right.

**Comment by bcoe** [comment]
@eljefedelrodeodeljefe moving some of the conversation here so I'm not spamming 1,000,000 people; I've got a hacking weekend planned this weekend, and will work on getting yargs patched such that it's backwards compatible.

Would love your help coming up with what the API should look like for `5.x`, definitely want to help people move in the correct direction.

**Comment by eljefedelrodeodeljefe** [comment]
Yeh, ditto. It's not easy looking at Node's source, tbh. I am gonna examine it from all sides. We'll see...

**Comment by bcoe** [comment]
@eljefedelrodeodeljefe closing in favor of this:

https://github.com/yargs/yargs/pull/501

1. I know I'm moments away from exiting, so it won't effect the upstream program to set `stdout/stderr` to blocking.
2. It ensures the program exits before the program using yargs has the opportunity to write any output.

**Comment by eljefedelrodeodeljefe** [comment]
👍

**Pull request closed without merging**
