### PR TITLE
Better Typescript Documentation

### LINKED ISSUE #1953: Typescript example doesn't compile
Hello,

I'm trying to use yargs with typescript but receive errors even after copying code from the docs.

The interesting part is that it starts to work after I `await` for result of argv.

image

Here is the text of error:

```
Element implicitly has an 'any' type because expression of type '"a"' can't be used to index type '{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; d: (string | number)[] | undefined; e: number; f: string | undefined; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; ... 4 more ...; $0: string; }>'.
  Property 'a' does not exist on type '{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; d: (string | number)[] | undefined; e: number; f: string | undefined; _: (string | number)[]; $0: string; } | Promise<{ [x: string]: unknown; a: boolean; b: string; c: number | undefined; ... 4 more ...; $0: string; }>'
```

Here is my tsconfig:
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "strict": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "outDir": "dist",
    "lib": ["ESNext"]
  },
  "include": ["./src/**/*"]
}

```
I'm using: 
```
"@types/yargs": "^17.0.0",
"yargs": "^17.0.1"
```

Thanks in advance

### PR DESCRIPTION
**Pull request by karizma**
- Added section for config

Technically `moduleResolution` and `strict` aren't needed for the examples shown, but I thought they would be good touches.

- [main] Added explanation for the union typing when calling `.argv` or `.parse`, and how to fix it.  
- Added title for the typing of `choices()`
- Stated the typescript config used

---

Should close #1953

### CODE REVIEW

**Comment by karizma** [comment]
@bcoe just a tiny reminder

This seems to be a pretty common issue, if you look at the replies of #1953. Is there anything wrong with the changes?

**Comment by bcoe** [comment]
@karizma thank you for the nudge, I've unfortunately had minimal time to put into open source recently.

I very much appreciate this PR and will prioritize looking as soon as possible.

**Comment by karizma** [comment]
No worries, completely understand.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@karizma thank you for clarifying the sync/async behavior 👏 

This should be a big help for TypeScript users.

**Pull request merged**
