### PR TITLE
Make strict() work with options containing hyphens

### LINKED ISSUE #1039: Hyphenated option breaks strict validation
Version: 10.0.3

Take this sample code:
```ts
import * as yargs from 'yargs';

yargs.option('awesome-arg', {
  string: true
}).strict().parse();

console.log('Parsed');
```

Running the sample with various arguments:
```
--awesomes-arg         // Strict mode is expected to fail here
--awesome-args         // and here
--awesomes-args        // here too
--awesomes-args --test // Strict mode only fails on `test`
--awesome-arg          // Strict mode successful as expected
```

### PR DESCRIPTION
**Pull request by andrewdotn**
Fixes #1039 #1171 #1236 #1325

### CODE REVIEW

**Comment by andrewdotn** [comment]
@bcoe Thanks! The `Fixes:` in the PR description seems to have done the auto-close-on-commit thing for only the first issue, so you may want to close #1171 #1236 #1325 as well.

**Comment by bcoe** [comment]
@andrewdotn could you please give the following a try:

```
npm i yargs@next
```

And let me know if everything is working as expected?

**Comment by andrewdotn** [comment]
@bcoe Yup, confirmed working, thanks!

Test file:

    const yargs = require('yargs');

    const argv = yargs
    .strict()
    .argv;

    console.log(argv);

Before:

    $ node foo.js --foo-bar
    { _: [], 'foo-bar': true, fooBar: true, '$0': 'foo.js' }

`yargs@next`:

    h$ node foo.js --foo-bar
    Options:
    --help     Show help                                                 [boolean]
    --version  Show version number                                       [boolean]

    Unknown arguments: foo-bar, fooBar
    Returned 1.

**Comment by bcoe** [comment]
@andrewdotn sorry that it took a while to get a release out the door; this work should now be available in `yargs@14.2.0`.

Let me know if you bump into any issues, and thank you for your contribution!

**Pull request merged**
