### PR TITLE
yargs 7.x

### PR DESCRIPTION
**Pull request by bcoe**
see: #742

### CODE REVIEW

**Comment by wtgtybhertgeghgtwtg** [comment]
Is the minimum required `node` version going to be bumped for `yargs@7.0.0`?

**Comment by lhecker** [comment]
@bcoe I'm currently facing the problem that, if I define subcommands, exceptions thrown by `coerce` don't cause yargs to abort the program anymore. I believe it's because of [those](https://github.com/yargs/yargs/blob/57a8490d3843acad83d387c782efc61e7facf1b7/lib/command.js#L158) [two](https://github.com/yargs/yargs/blob/57a8490d3843acad83d387c782efc61e7facf1b7/lib/command.js#L173) lines. Since they pass `true` as the `_skipValidation` parameter [this](https://github.com/yargs/yargs/blob/57a8490d3843acad83d387c782efc61e7facf1b7/yargs.js#L1048-L1049) block of code will never be executed and thus the value of `parsed.error` is essentially thrown away!

**Comment by bcoe** [comment]
@lhecker I think you're right, `if (parsed.error) throw new YError(parsed.error.message)` should be pulled into the new `_validation` helper -- mind opening a ticket, or _still_ a pull request against the `7.x` branch?

**Comment by lhecker** [comment]
@bcoe I don't really feel that comfortable working on yargs yet as in fact I only started using this library yesterday. For instance I really don't know what this "`_validation` helper" is. 😅 But since the fix is surely very easy to write the easiest way is probably if you fix it yourself - If you don't mind of course. 🙂

**Comment by bcoe** [comment]
@lhecker I'm actually at a hacking event all weekend, working on getting new folks onboarded to yargs ... my point being, if you're interested in contributing, give it a shot 👍 nothing to be embarrassed about.

**Pull request merged**
