### PR TITLE
chore(linting): switch from standard to gts 2.x

### PR DESCRIPTION
**Pull request by mleguen**
Follow-up of @bcoe's suggestion in #1587

### CODE REVIEW

**Comment by mleguen** [comment]
@bcoe Looks like gts is not working with node 8. This is confirmed by its package.json:
```json
  "engines": {
    "node": ">=10"
  },
```

So this switch will have to wait...

**Comment by bcoe** [comment]
@mleguen `gts` is officially at `2.x.x` 🎉, also I've been thinking a lot on the topic ([I wrote this blog post on the subject for Node.js](https://medium.com/the-node-js-collection/maintainers-should-consider-following-node-js-release-schedule-ab08ed4de71a)) and would like to drop Node 8 soon.

How do you feel about releasing the last version of `15.x.x` soon (with your initial support for TypeScript), and then moving towards the next `major`, with `gts`, Node 8 being dropped, and any breaking TypeScript changes we need to take on, .e.g., rewriting index.js and yargs.js.

**Comment by mleguen** [comment]
When we drop nodejs 8 support, we should not forget to remove explicit es2017 target in tsconfig.json, to keep the es2018 one from gts default tsconfig.json.

**Comment by bcoe** [comment]
this has gotten a little stale, and I'm not convinced it's worth the trouble if  `standardx` is working for us, let's stick with `standardx` for now.

**Pull request closed without merging**
