### PR TITLE
Add Norwegian Nynorsk translations

### PR DESCRIPTION
**Pull request by severen**
I've added translations for Nynorsk, which is the other official written standard for the Norwegian language. I've based it off the Bokmål translations, so the terminology *should* be consistent.

### CODE REVIEW

**Comment by bcoe** [comment]
@severen this is awesome, thank you 👍

**Comment by severen** [comment]
🎉

**Comment by bcoe** [comment]
@severen please try:

`npm i yargs@next` it should have the Norwegian translation; please let me know if you run into any issues, and thanks for the contribution.

**Comment by severen** [comment]
Everything seems to be working perfectly as far as I can tell.

**Pull request merged**
