### PR TITLE
ci: test with node 6 once 6.4.0 is patched

### LINKED ISSUE #596: Different util.inspect output making tests fail
As #595 has shown, builds now fail with Node.js v6.4.0.

As it turns out, the tests fail because of [this one test](https://github.com/yargs/yargs/blob/master/test/yargs.js#L421). It tests for yarg's output when a command is supplied that does not have a name. When yargs is about to output that error, it also uses `util.inspect` to show the content of the supplied command object [(reference)](https://github.com/yargs/yargs/blob/master/lib/command.js#L70).

The test output shows that this very output is expected to be slightly different. The original object is:
```javascript
{ desc: 'A command with no name',
  builder: [Function],
  handler: [Function] }
```

Interestingly, using `util.inspect()` on this object generates different outputs on different minors of Node.js v6:

v6.3.1:
```
'{ desc: \'A command with no name\',\n  builder: [ [Function: Function] ],\n  handler: [ [Function: Function] ] }'
```

v6.4.0:
```
'{ desc: \'A command with no name\',\r\n  builder: [ [Function: Function] ],\r\n  handler: [ [Function: Function] ] }'
```

I'm not sure if this is intended behaviour, so I'll report it on the Node.js repo.

### PR DESCRIPTION
**Pull request by nexdrew**
Reverts the Travis and AppVeyor changes deliberately introduced with #597.

It is expected that tests with Node 6 will fail until version 6.4.0 is patched with this reversion: nodejs/node#8143

This PR serves as a reminder to revert the temporary testing change pinned to Node 6.3.1.

Fixes #596.

Thanks to @maxrimue for originally reporting the error, and thanks to @addaleax for fixing our tests with citgm and AppVeyor!

### CODE REVIEW

**Comment by addaleax** [comment]
btw, I know this isn’t communicated suuuper-well, but Node v5 is already past its end of life, as far as Node core is concerned.

**Comment by nexdrew** [comment]
@addaleax Hmm, good point. I'll drop Node 5 with this too. :+1:

**Comment by addaleax** [comment]
v6.5.0 is out, so kicking off a new CI with this should return everything to green :)

**Comment by nexdrew** [comment]
@addaleax Thanks for the heads up, will push a new commit dropping Node 5 very soon.

**Comment by nexdrew** [comment]
Looks like it's gonna fail with Node 6.5.0 since the Function descriptors now include the function name (e.g. `builder: [Function: builder]` instead of `builder: [Function]`).

Time to relax the regex methinks.

**Comment by addaleax** [comment]
Oh, yeah, I forgot that… the Node.js core tests had to be fixed up for that, too. You’re probably right.

**Comment by nexdrew** [comment]
Tests are green again so I'm gonna squash-and-merge this. Thanks to @addaleax and @maxrimue for your help!

**Comment by maxrimue** [comment]
Great, thanks @nexdrew :tada:

**Pull request merged**
