### PR TITLE
chore: use const as a semantic tool

### PR DESCRIPTION
**Pull request by jameswomack**
Philosophy behind this: http://womack.io/2016/01/05/Const-ant-Craving/
tldr;
* `const` has been supported in Node.js since at least 0.4
* `const` makes code more readable—it's clear a value won't change
* standard helps w/ this by pointing out when `const` is misused

### CODE REVIEW

**Comment by lrlna** [comment]
That's cool! I think we were talking about whether or not we would want to be transitioning more into ES6 stuff back in February (can't remember what the jury decided on that). This could be a nice transition over ✨

**Comment by bcoe** [comment]
@jameswomack this is great 👍 I have a big block of time to work on OSS on this weekend, and will land the heck out of tickets.

**Comment by nexdrew** [comment]
TIL `const` goes back to Node 0.6. Wow.

Nice writeup @jameswomack. Good work!

**Comment by jameswomack** [comment]
Thanks everyone. Yeah, I found [a Chromium/V8 issue](https://bugs.chromium.org/p/v8/issues/detail?id=327) regarding basic `const` support that's dated Apr 24, 2009!

**Comment by bcoe** [comment]
rebased here: https://github.com/yargs/yargs/pull/502

**Pull request closed without merging**
