### PR TITLE
fix: translation not working when using __ with a single parameter

### PR DESCRIPTION
**Pull request by jjoselv**
Closes yargs/yargs#1101

### CODE REVIEW

**Comment by nexdrew** [comment]
@jjoselv Good find! I verified locally that this one i18n message was not being properly translated and that your change fixes it. I then wrote a test for it and pushed it to your fork, which added it to this PR.

On top of this, would you be able to provide any proper translations of the i18n string in other languages? If so, you could add those translations to this PR, if you want. Otherwise, we can worry about that later.

Thanks again!

**Comment by jjoselv** [comment]
If all is well, can this PR be merged by someone please?

**Comment by bcoe** [comment]
@jjoselv this should now be fixed \o/ please try `npm i yargs@next`; if the release is looking good, I will promote it next week.

**Comment by jjoselv** [comment]
It works. Good to go. I'll update the i18n files at some point in time...

**Pull request merged**
