### PR TITLE
docs: add link to website repo in contributing docs

### PR DESCRIPTION
**Pull request by glenwinters**
This adds a short note to the contributing docs about how to contribute to the website since I had a hard time finding how to serve the docs locally.

### CODE REVIEW

**Comment by mleguen** [comment]
@glenwinters I discovered this repo with your PR :-)

@bcoe Do we consider yargs.org website to still be maintained? I stopped using it as it described an outdated version of yargs, and the docs directory in the yargs repo is enough for me.

**Comment by glenwinters** [comment]
@mleguen Ha! That's funny.

`yargs.org` is the 3rd and 4th hit on google when you search for `yargs` and I found the front page example and API docs page helpful, so perhaps it's worth making some updates.

**Comment by bcoe** [comment]
I would rather us link to http://yargs.js.org/, I would love for us to make sure this website is dusted off and up to date, just not something I've had cycles for...

I feel like the build step broke a couple years ago and I haven't dug into it.

**Comment by glenwinters** [comment]
@bcoe Sorry, I meant yargs.js.org, not yargs.org. That was a typo.

In this PR, I'm linking to the github repo since this is in the contributing docs section.

**Comment by bcoe** [comment]
:+1: gotcha, I understand your intention now.

**Pull request merged**
