### PR TITLE
feature: add method to hide option extras

### PR DESCRIPTION
**Pull request by jly36963**
Addresses: https://github.com/yargs/yargs/issues/2153

## Description

Given the following:

```js
yargs('cmd1 --help')
  .command(
    'cmd1',
    'cmd1 desc',
    yargs => yargs
      .option('opt1', {
        type: 'string',
        choices: ['foo', 'bar', 'baz'],
        alias: 'o',
        required: true,
        description: "A long description that might break formatting"
      }),
    argv => console.log(argv)
  )
  .hideOptionExtras()
  .strict()
  .parse()
```

The `hideOptionExtras` would cause the following output

```
cmd1 desc

Options:
      --help     Show help                                             [boolean]
      --version  Show version number                                   [boolean]
  -o, --opt1     A long description that might break formatting
                              [string] [required] [choices: "foo", "bar", "baz"]
```

to look like this instead

```
cmd1 desc

Options:
      --help     Show help
      --version  Show version number
  -o, --opt1     A long description that might break formatting
```

## Questions

If this works, I'll add unit tests.
What other things would need to change? (docs, examples, etc)

### CODE REVIEW

**Review by bcoe — CHANGES_REQUESTED** [review]
@jly36963 this is great work, thank you :clap: 

One ask, would it be possible to add this setting in the list here: https://github.com/yargs/yargs/blob/main/docs/api.md#parserconfigurationobj

**Review by bcoe — APPROVED** [review]

**Review by bcoe — APPROVED** [review]
Love this. I think `usageConfiguration` will help us provide nuanced configuration without adding 1,000,000 additional methods.

**Comment by ljharb** [comment]
I’m a bit confused; how can i show types in general, but hide types for an a specific option?

**Comment by jly36963** [comment]
@ljharb I don't think there is a way currently. It would likely be a new property on option/positional objects like `hideUsageTypes`, or potentially a refactor on the usage logic to allow for customizations.

I won't be involved with this package much in the future, so I won't be much help in implementing this change

**Comment by ljharb** [comment]
In that case, this does not solve #1145, thanks for confirming.

**Pull request merged**
