### PR TITLE
docs: Fix example of coerce

### PR DESCRIPTION
**Pull request by regseb**
The first example of [`.coerce(key, fn)`](https://yargs.js.org/docs/#api-reference-coercekey-fn) is invalid: an `await` is used in a non-`async` function.

```js
var argv = require('yargs/yargs')(process.argv.slice(2))
  .coerce('file', function (arg) {
    return await require('fs').promises.readFile(arg, 'utf8')
  })
  .argv
```

### CODE REVIEW

**Comment by shadowspawn** [comment]
Making the examples correct is a good thing. The example was updated as part of adding async support to `.coerce()` in https://github.com/yargs/yargs/pull/1872 but was not complete, and I would rather make the example work with async than remove the async. 

Would you like to do that?

**Comment by regseb** [comment]
I modified the example to add an `async` / `await`.

**Comment by shadowspawn** [comment]
I like the direction of getting away from `require` embedded in the code.

It is much easier to run the example in a module where top-level await is available. How about about making this example esm? e.g.

```js
import { readFile } from 'node:fs/promises';
import yargs from 'yargs';
const argv = await yargs(process.argv.slice(2))
   .coerce('file', async (arg) => readFile(arg, 'utf8'))
   .parseAsync();
```

**Comment by regseb** [comment]
In your example, the `async` is useless because the function has no `await` ([_require-await_](https://eslint.org/docs/latest/rules/require-await)). It would be useless to add an `await` before the return: `.coerce('file', async (arg) => await readFile(arg, 'utf8'))` ([_no-return-await_](https://eslint.org/docs/latest/rules/no-return-await)).

I propose to add an intermediate variable (which is useless, but there is no ESLint rule to detect it) to have an excuse to use an `await`.

```js
import { readFile } from 'node:fs/promises';
import yargs from 'yargs';
const argv = await yargs(process.argv.slice(2))
  .coerce('file', async (arg) => {
    const content = await readFile(arg, 'utf8');
    return content;
  })
  .parseAsync();
```

**Comment by shadowspawn** [comment]
Good points. I suggest adding `JSON.parse` on the contents. Then the `await ` is needed and the async function makes sense.

**Comment by regseb** [comment]
I added `JSON.parse()` in the example.

**Review by shadowspawn — APPROVED** [review]
LGTM

**Comment by shadowspawn** [comment]
Thanks for the PR and conversation @regseb.

**Review by bcoe — APPROVED** [review]

**Pull request merged**
