### PR TITLE
fix(lang): fix "Not enough non-option arguments" message for the Czech language

### PR DESCRIPTION
**Pull request by mlc-mlapis**
Removing an extra comma at the end of the line.

### CODE REVIEW

**Review by Betakaro — APPROVED** [review]

**Review by adamjedlicka — APPROVED** [review]

**Review by vtregner-cen29414 — APPROVED** [review]

**Comment by mlc-mlapis** [comment]
It seems that an additional formal step is still required. What is it? Can I help with it?

**Comment by mlc-mlapis** [comment]
It's a very trivial issue (only a typo, in fact)  and simple to review. Why it takes so much time to merge?

**Review by xmedeko — APPROVED** [review]

**Comment by xmedeko** [comment]
@mlc-mlapis It needs to be approved by some maintainer: review is required by reviewers with **write access**.

**Comment by mlc-mlapis** [comment]
@xmedeko Thanks for the help.

**Comment by mlc-mlapis** [comment]
@bcoe @nexdrew @nexdrew @maxrimue @lrlna Can you help, please? The latest 17.6.0 release is unusable.

**Review by nexdrew — APPROVED** [review]
Verified that this fixes the problem. Thanks for the contribution!

**Comment by nexdrew** [comment]
Bug introduced in https://github.com/yargs/yargs/pull/2220

**Comment by nexdrew** [comment]
@bcoe I'm not familiar with the tag/release protocol of yargs anymore, otherwise I would squash and merge this to prepare a 17.6.1 patch release.

Can we get a little help here, since this is affecting `nx` users? Thanks, hoping you're doing well!

**Comment by davidslaby** [comment]
I join @nexdrew's pleas. As `nx` user, I'm not able to run some commands. @bcoe could you help to release patch version, please? Thanks in advance!

**Review by rajtslegr — APPROVED** [review]

**Comment by jirihybek** [comment]
Since this was not merged yet (a typo, in 25 days, really?) and it's breaking the nx package, I've found the following workaround. It may help someone.

Run node process with env var `LANG` like this: `LANG=en_US npx create-nx-workspace...`.

**Comment by nexdrew** [comment]
I'll go ahead and merge it. Will have to figure out how to get a 17.6.1 release published.

Yargs is used by thousands of projects, and is (or at least was) used as a canary-in-the-goldmine package to help verify regressions of Node itself, so releases carry a lot of weight.

Perhaps @bcoe has been able to automate everything via [release-please](https://www.npmjs.com/package/release-please). Will see.

**Pull request merged**
