### PR TITLE
Upgrade string-width

### PR DESCRIPTION
**Pull request by adam2k**
Related to https://github.com/chalk/ansi-regex/commit/8d1d7cdb586269882c4bdc1b7325d0c58c8f76f9

Additional information CWE-400 https://cwe.mitre.org/data/definitions/400.html

### CODE REVIEW

**Comment by adam2k** [comment]
@bcoe or @substack can I get maintainer approval to run workflows?  I haven't contributed to this repo yet, so let me know if there is some other way I should request access.  Thanks!

**Comment by ljharb** [comment]
Noting: string-width v5 requires node 12 while v4 requires node 8, luckily this isn't a breaking change for yargs since it already requires node 12.

However, string-width v5 is ESM-only, which means it can't be `require`d, which means yargs likely can't use it.

I'd suggest finding an alternative dependency that isn't ESM-only and also lacks the CVE.

**Comment by bcoe** [comment]
@ljharb @adam2k the ESM version of yargs already dropped using `string-width`, ironically because at the time `string-width` wasn't ESM.

The alternate implementation is [here](https://github.com/yargs/yargs/blob/master/lib/platform-shims/esm.mjs#L61).

I suggest we just switch to this approach for both ESM and CJS, the downside is that string width will be slightly off for some unicode characters I believe (_am I correct in my understanding that some unicode characters are two ascii characters wide?_).

Either way, I think this is a minor regression, and worth dropping a dep.

**Comment by ljharb** [comment]
@bcoe that alternate implementation is quite wrong for many things - the spread operator only splits to code points, but many emojis are multiple code points - `'🏳️‍🌈'` for example, has a length of 6 and contains 4 code points.

A proper replacement would likely require using `Intl.Segmenter` and splitting by grapheme clusters, and then checking the resulting array length.

**Comment by woehr** [comment]
The path of least resistance here would probably be to see whether strip-ansi will backport a dependency bump to address the CVE and then to get string-width 4.2.2 to update the strip-ansi dependency. I've asked whether strip-ansi can do a hotfix here: https://github.com/chalk/strip-ansi/issues/40.

**Comment by bcoe** [comment]
@Qix- kindly back-ported a fix to `ansi-regex@5.0.1`, so we should be good now 👍 

https://github.com/chalk/ansi-regex/issues/38

**Pull request closed without merging**
