### PR TITLE
Add browser.d.ts and check for existence of Error.captureStackTrace()

### PR DESCRIPTION
**Pull request by codetheweb**
I'm attempting to use this in a browser environment and have run into a few issues.

### CODE REVIEW

**Comment by bcoe** [comment]
Thanks for the patch 😄 

@codetheweb in Chromium at least, `Error.captureStackTrace` is a method. I'm curious what environment is giving you trouble?

**Comment by codetheweb** [comment]
It's not available in Firefox unfortunately.

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@codetheweb thank you for the contribution.

**Comment by hongaar** [comment]
The `browser.d.ts` is not available from NPM, added a commit to https://github.com/yargs/yargs/pull/2185 to address this.

**Pull request merged**
