### PR TITLE
fix: exit after async handler done

### PR DESCRIPTION
**Pull request by PengBoUESTC**
#2312

### CODE REVIEW

**Comment by shadowspawn** [comment]
Thanks. My suspicion is adding a callback is a work-around for the async handling not being correct. But it does seem to work! It will take me a while to understand the call paths.

**Comment by PengBoUESTC** [comment]
> Thanks. My suspicion is adding a callback is a work-around for the async handling not being correct. But it does seem to work! It will take me a while to understand the call paths.

callback is not a good idea, i did this because `showHelp ` is not declared  as an async function, I don't want to make a break change

**Comment by shadowspawn** [comment]
`.showHelp()` can take a callback already, so do not need to add another one.

```
          this.showHelp(message => {
            this.#logger.log(message);
            this.exit(0);
          });
```

**Comment by shadowspawn** [comment]
Ideally we would like a unit test for any code changes. Are you up for that?

(I have not looked at how to do this. I assume will need a little setup to prepare for an async operation that calls exit!)

**Comment by PengBoUESTC** [comment]
> Ideally we would like a unit test for any code changes. Are you up for that?
> 
> (I have not looked at how to do this. I assume will need a little setup to prepare for an async operation that calls exit!)

it's not easy to give a test case =_=

**Comment by shadowspawn** [comment]
I'll have a look at doing a test.

**Comment by shadowspawn** [comment]
I got a test working, but uncovered an interesting issue in the process. I think the async triggered during the help processing is not returned as a promise, so calling await on the parse result does not block and allow the help to display before the test completes. I think this PR still makes sense on its own so not considering that a blocker! I'll open a PR to your branch.

**Review by shadowspawn — APPROVED** [review]
I think this is a simple change that should work same way for sync and more usefully for async.

**Pull request merged**
