### PR TITLE
fix(i18n): Japanese translation phrasing

### PR DESCRIPTION
**Pull request by hogashi**
Fixed 3 issues of Japanese translation described in #1617

### CODE REVIEW

**Comment by mleguen** [comment]
Thank you @hogashi .

I add this review to my TODO, but I'm afraid I won't be able to have some time for it before next week.

**Comment by hogashi** [comment]
@mleguen Of course that's OK! Don't hurry and review it whenever you like 👍

**Comment by bcoe** [comment]
@hogashi 👍 contribution is much appreciated.

**Comment by hogashi** [comment]
Thank you, @bcoe ! I'm glad to contribute to this awesome project :star: / Would you take care of the issue #1617, or may I close it right now?

**Pull request merged**
