### PR TITLE
docs(api): add description for coerce behavior for array type argument

### PR DESCRIPTION
**Pull request by yxliang01**
This fixes https://github.com/yargs/yargs/issues/1389 . The wording I feel is not so ideal. Maybe suggestions needed.

### CODE REVIEW

**Comment by bcoe** [comment]
:+1: I like @mleguen's edit; mind making the update @yxliang01?

**Comment by yxliang01** [comment]
Thanks @mleguen @bcoe for your suggestions! The changes have been made. :)

**Comment by mleguen** [comment]
The CI failing is weird, as it is coming from tests unrelated with any changes in this PR?

**Comment by mleguen** [comment]
The CI is failing on tests which are neither in the branch to merge, nor in the master branch.

I find these failing tests in a commit from @laggingreflex, in its fork, for which I can see a CI build failure in Travis.

@bcoe Is something wrong with Travis?

**Comment by yxliang01** [comment]
@mleguen Yep. This only changes documentation - shouldn't affect CI result at all. I think for this PR, CI can be ignored? :)

**Pull request merged**
