### PR TITLE
doc: clarify parserConfiguration object structure

### PR DESCRIPTION
**Pull request by bcoe**
CC: @plroebuck.

### CODE REVIEW

**Comment by bcoe** [comment]
@plroebuck would this note have helped clarify configuration settings for you?

**Comment by plroebuck** [comment]
Not as much as a codefence example would have....

**Comment by plroebuck** [comment]
Reference #1303

**Comment by bcoe** [comment]
@plroebuck I'm not quite sure what you mean by a code-fence example, mind submitting something?

My concern is that I don't want yargs to have to duplicate 100% of yargs-parser's documentation; we have quite a few configuration settings available to users.

**Pull request merged**
